version: '3'
services:
    backend:
        build:
            context: ./backend
        ports:
            - "8080:8080"
    frontend:
        image: node:13
        volumes:
            - ./frontend:/app
        entrypoint: ["npm", "start"]
        working_dir: /app
